apiVersion: v1
kind: Service
metadata:
  name: my-main-svc
  labels:
    app: main
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 8088
    name: ssh
    targetPort: 8081
  selector:
    app: main
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-sample
  labels:
    app: main
spec:
  replicas: 3
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
      - name: main-sample
        image: juliusmas/main-node-sample
        ports:
        - containerPort: 8081
